In [28]:
import pandas as pd
import os
from datetime import date

In [29]:
# Get the current date
todays_date = date.today()
year = str(todays_date.year)
if todays_date.month < 10:
    month = '0'+str(todays_date.month)
else:
    month = str(todays_date.month)

if todays_date.day < 10:
    day = '0'+str(todays_date.day)
else:
    day = str(todays_date.day)

current_date = year+month+day
directory_name = 'results/'+current_date
if not os.path.isdir(directory_name):
    os.mkdir(directory_name)
    
directory_name

'results/20260507'

In [17]:
TWP_PredictionSets = pd.read_csv('/Users/eochoa/Downloads/TWP_PredictionSets.csv')
#del TWP_PredictionSets['Unnamed: 0']
TWP_PredictionSets = TWP_PredictionSets.sort_values(['Sample Type', 'DAR '])

In [36]:
CP_results_active_paired = pd.read_csv('results/20250922/CP_results_active_paired.csv')
del CP_results_active_paired['Unnamed: 0']

CP_results_active_unpaired_ir = pd.read_csv('results/20250922/CP_results_active_unpaired_ir.csv')
del CP_results_active_unpaired_ir['Unnamed: 0']

CP_results_active_unpaired_raman = pd.read_csv('results/20250922/CP_results_active_unpaired_raman.csv')
del CP_results_active_unpaired_raman['Unnamed: 0']


CP_results_passive_paired = pd.read_csv('results/20250922/CP_results_passive_paired.csv')
del CP_results_passive_paired['Unnamed: 0']

CP_results_passive_unpaired_ir = pd.read_csv('results/20250922/CP_results_passive_unpaired_ir.csv')
del CP_results_passive_unpaired_ir['Unnamed: 0']

CP_results_passive_unpaired_raman = pd.read_csv('results/20250922/CP_results_passive_unpaired_raman.csv')
del CP_results_passive_unpaired_raman['Unnamed: 0']



CP_results = pd.concat([
    CP_results_active_paired,
    CP_results_active_unpaired_ir,
    CP_results_active_unpaired_raman,
    CP_results_passive_paired,
    CP_results_passive_unpaired_ir,
    CP_results_passive_unpaired_raman
], axis=0).reset_index(drop=True)
CP_results

,id,prection_set_ir,prection_set_raman,prection_set_mvcp,polymer_flopp,hqi_flopp,id_top_match_flopp,polymer_slopp,hqi_slopp,id_top_match_slopp
0,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...,['Polymethyl Methacrylate'],"['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Polymethyl Methacrylate', 'Polyurethane', 'R...",Polymethyl Methacrylate,0.918139,PMMA 1. Orange Fragment.CSV,Polyamide,0.908069,Polyamide 1. Blue Fragment.txt
1,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...,"['Polystyrene', 'Polyurethane']","['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Polyamide', 'Polystyrene', 'Polyurethane']",Polystyrene,0.906415,PS 8. White Foam.CSV,Polyvinyl Chloride,0.919405,Polyvinyl Chloride 2. Clear Fragment.txt
2,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...,"['Polypropylene', 'Polystyrene', 'Polyurethane']","['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Acrylonitrile Butadiene Styrene', 'Polypropy...",Polypropylene,0.906320,PP 38. Blue Fragment.CSV,Polypropylene,0.914084,Polypropylene 14. Green Fiber.txt
3,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...,"['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Acrylic', 'Acrylonitrile Butadiene Styrene',...",Polypropylene,0.909396,PP 23. Yellow Fragment.CSV,Polypropylene,0.913821,Polypropylene 14. Green Fiber.txt
4,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...,"['Polymethyl Methacrylate', 'Polyurethane', 'R...","['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Polymethyl Methacrylate', 'Polyurethane', 'R...",Polymethyl Methacrylate,0.905225,PMMA 1. Orange Fragment.CSV,Polypropylene,0.912531,Polypropylene 14. Green Fiber.txt
...,...,...,...,...,...,...,...,...,...,...
11244,DC_passive_MarApr2024_C9_20240612_192,NaN,"['Polyamide', 'Polyethylene', 'Polyethylene Vi...",NaN,NaN,NaN,NaN,Rubber,0.931361,Rubber 3. Red Fiber (Styrene-Isoprene).txt
11245,DC_passive_MarApr2024_C9_20240612_195,NaN,"['Acrylic', 'Acrylonitrile Butadiene Styrene',...",NaN,NaN,NaN,NaN,Polypropylene,0.916357,Polypropylene 14. Green Fiber.txt
11246,DC_passive_MarApr2024_C9_20240612_197,NaN,"['Acrylic', 'Acrylonitrile Butadiene Styrene',...",NaN,NaN,NaN,NaN,Polypropylene,0.917183,Polypropylene 14. Green Fiber.txt
11247,DC_passive_MarApr2024_C9_20240612_198,NaN,"['Acrylic', 'Acrylonitrile Butadiene Styrene',...",NaN,NaN,NaN,NaN,Polypropylene,0.908972,Polypropylene 14. Green Fiber.txt
11248,DC_passive_MarApr2024_C9_20240612_202,NaN,"['Acrylic', 'Acrylonitrile Butadiene Styrene',...",NaN,NaN,NaN,NaN,Polypropylene,0.917218,Polypropylene 14. Green Fiber.txt

In [40]:
CP_results_active_paired = pd.read_csv('results/20251026/CP_results_active_paired_ir_LikelyMPs.csv')
del CP_results_active_paired['Unnamed: 0']
CP_results_active_paired

,top_1,top_2,top_3,top_4,top_5,top_6,top_7,top_8,top_9,top_10,...,id_top_match_flopp_Polyethylene,id_top_match_flopp_Polyethylene Terephthalate,id_top_match_flopp_Polyethylene Vinyl Acetate,id_top_match_flopp_Polymethyl Methacrylate,id_top_match_flopp_Polypropylene,id_top_match_flopp_Polystyrene,id_top_match_flopp_Polyurethane,id_top_match_flopp_Polyvinyl Chloride,id_top_match_flopp_Rubber,id
0,Polymethyl Methacrylate,NaN,Rubber,NaN,NaN,NaN,NaN,NaN,Polypropylene,NaN,...,NaN,NaN,NaN,PMMA 1. Orange Fragment.CSV,PP 6. Red Fragment.CSV,NaN,NaN,NaN,R 8. White Bike Tire Fragment.CSV,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
1,Polymethyl Methacrylate,Rubber,Polyurethane,NaN,NaN,NaN,Polypropylene,NaN,NaN,NaN,...,NaN,NaN,NaN,PMMA 1. Orange Fragment.CSV,PP 64. Blue Fiber.CSV,NaN,PU 7. Yellow Packaging Foam.CSV,NaN,R 8. White Bike Tire Fragment.CSV,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
2,Polystyrene,Polypropylene,Polyamide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,PP 38. Blue Fragment.CSV,PS 13. Pink Spoon Fragment.CSV,NaN,NaN,NaN,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
3,Polystyrene,Polypropylene,Polyurethane,Polyamide,Rubber,Polyethylene Terephthalate,NaN,NaN,NaN,NaN,...,NaN,PET 15. Black Cable Cover Fragment.CSV,NaN,NaN,PP 38. Blue Fragment.CSV,PS 13. Pink Spoon Fragment.CSV,PU 2. Orange Foam.CSV,NaN,R 3. White Shoe Sole Fragment.CSV,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
4,Polypropylene,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Polyvinyl Chloride,NaN,...,NaN,NaN,NaN,NaN,PP 62. Orange Fiber.CSV,NaN,NaN,PVC 1. Clear Fragment.CSV,NaN,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,Polypropylene,Polystyrene,Rubber,Polyethylene,Polyurethane,Polyamide,Acrylonitrile Butadiene Styrene,Polyvinyl Chloride,NaN,NaN,...,PE 34. Black Fragment.CSV,NaN,NaN,NaN,PP 38. Blue Fragment.CSV,PS 6. White Foam.CSV,PU 2. Orange Foam.CSV,PVC 23. Pink Yoga Mat Foam.CSV,R 6. Black Bike Tire Fragment.CSV,MEC_02_119_DC_Active_20240418_S6_ThinSi_202410...
295,Polyurethane,Rubber,Polypropylene,Polystyrene,Polyethylene,Polyethylene Terephthalate,Polyvinyl Chloride,Polyamide,Acrylonitrile Butadiene Styrene,Cellulose Acetate,...,PE 34. Black Fragment.CSV,Polyester 7. Red Yarn Fiber.CSV,EVA 3. Grey Foam.CSV,PMMA 1. Orange Fragment.CSV,PP 43. Green Fragment.CSV,PS 6. White Foam.CSV,PU 2. Orange Foam.CSV,PVC 23. Pink Yoga Mat Foam.CSV,R 6. Black Bike Tire Fragment.CSV,MEC_02_119_DC_Active_20240418_S6_ThinSi_202410...
296,Polystyrene,Rubber,Polyurethane,Polypropylene,Polyethylene,Polyamide,Acrylonitrile Butadiene Styrene,NaN,NaN,NaN,...,PE 34. Black Fragment.CSV,NaN,NaN,NaN,PP 43. Green Fragment.CSV,PS 6. White Foam.CSV,PU 2. Orange Foam.CSV,NaN,R 6. Black Bike Tire Fragment.CSV,MEC_02_119_DC_Active_20240418_S6_ThinSi_202410...
297,Polystyrene,Polypropylene,Rubber,Polyurethane,Polyethylene,Polyamide,Polyvinyl Chloride,Polyethylene Terephthalate,Acrylonitrile Butadiene Styrene,Polyethylene Vinyl Acetate,...,PE 34. Black Fragment.CSV,PET 15. Black Cable Cover Fragment.CSV,EVA 3. Grey Foam.CSV,PMMA 1. Orange Fragment.CSV,PP 43. Green Fragment.CSV,PS 6. White Foam.CSV,PU 2. Orange Foam.CSV,PVC 23. Pink Yoga Mat Foam.CSV,R 6. Black Bike Tire Fragment.CSV,MEC_02_119_DC_Active_20240418_S6_ThinSi_202410...
298,Polypropylene,Rubber,Polyvinyl Chloride,Polyethylene,Polyethylene Vinyl Acetate,Acrylonitrile Butadiene Styrene,Polycarbonate,Polyethylene Terephthalate,Polyurethane,Acrylic,...,PE 14. Green Tampon Wrapper Film.CSV,PET 8. Black Fiber.CSV,PEVA 8. Green Flip Flop Foam.CSV,PMMA 1. Orange Fragment.CSV,PP 1. White Fragment.CSV,PS 18. Clear Fragment.CSV,PU 17. Clear Fragment.CSV,PVC 1. Clear Fragment.CSV,R 2. Black Bike Handle Cover Foam.CSV,MEC_02_119_DC_Active_20240418_S6_ThinSi_202410...

In [41]:
CP_results_active_paired = pd.read_csv('results/20251026/CP_results_active_paired_raman_LikelyMPs.csv')
del CP_results_active_paired['Unnamed: 0']
CP_results_active_paired

,top_1,top_2,top_3,top_4,top_5,top_6,top_7,top_8,top_9,top_10,...,top_6_hqi,top_7_hqi,top_8_hqi,top_9_hqi,top_10_hqi,top_11_hqi,top_12_hqi,top_13_hqi,top_14_hqi,id
0,Polypropylene,Rubber,NaN,NaN,NaN,NaN,NaN,NaN,Polymethyl Methacrylate,NaN,...,NaN,NaN,NaN,0.045032,NaN,NaN,NaN,NaN,NaN,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
1,Polypropylene,NaN,NaN,NaN,Polymethyl Methacrylate,NaN,NaN,Rubber,NaN,NaN,...,NaN,NaN,0.015404,NaN,NaN,NaN,NaN,0.009608,NaN,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
2,Polypropylene,NaN,NaN,NaN,NaN,Polystyrene,NaN,NaN,NaN,NaN,...,0.029359,NaN,NaN,NaN,NaN,NaN,NaN,0.007021,NaN,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
3,Rubber,Polyethylene Terephthalate,Polyamide,Polystyrene,Polypropylene,NaN,NaN,NaN,Polyurethane,NaN,...,NaN,NaN,NaN,0.032683,NaN,NaN,NaN,NaN,NaN,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
4,Polyvinyl Chloride,NaN,Polypropylene,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,Polypropylene,NaN,Polyvinyl Chloride,NaN,Polystyrene,Rubber,NaN,Polyamide,Polyethylene,Polyurethane,...,0.053028,NaN,0.031099,0.029368,0.028578,0.023030,NaN,NaN,NaN,MEC_02_119_DC_Active_20240418_S6_ThinSi_202410...
295,Rubber,Polyamide,Polyethylene Terephthalate,Polyethylene,Polystyrene,Polypropylene,Acrylonitrile Butadiene Styrene,Polyvinyl Chloride,Polyurethane,Cellulose Acetate,...,0.072997,0.067930,0.053746,0.030780,0.026476,NaN,0.018621,0.017797,0.016579,MEC_02_119_DC_Active_20240418_S6_ThinSi_202410...
296,Polypropylene,Polyethylene,Rubber,Polystyrene,Polyamide,NaN,NaN,Polyurethane,NaN,NaN,...,NaN,NaN,0.055674,NaN,NaN,0.032058,NaN,NaN,NaN,MEC_02_119_DC_Active_20240418_S6_ThinSi_202410...
297,Rubber,Polyethylene Terephthalate,Polyethylene,Polyamide,Polypropylene,Polystyrene,Polyvinyl Chloride,Acrylonitrile Butadiene Styrene,Polyurethane,Cellulose Acetate,...,0.084466,0.062095,0.051254,0.040103,0.030337,0.027961,NaN,0.019110,0.012639,MEC_02_119_DC_Active_20240418_S6_ThinSi_202410...
298,Polypropylene,Polyethylene Terephthalate,Polycarbonate,Polyvinyl Chloride,Polymethyl Methacrylate,Polystyrene,Rubber,Polyethylene,NaN,Acrylonitrile Butadiene Styrene,...,0.029107,0.020536,0.018318,NaN,0.015607,NaN,0.010986,0.010841,0.005928,MEC_02_119_DC_Active_20240418_S6_ThinSi_202410...

In [36]:
CP_results_active_paired = pd.read_csv('results/20251026/CP_results_active_paired_ir_LikelyMPs.csv')
del CP_results_active_paired['Unnamed: 0']

CP_results_active_unpaired_ir = pd.read_csv('results/20251026/CP_results_active_unpaired_ir.csv')
del CP_results_active_unpaired_ir['Unnamed: 0']

CP_results_active_unpaired_raman = pd.read_csv('results/20251026/CP_results_active_unpaired_raman.csv')
del CP_results_active_unpaired_raman['Unnamed: 0']


CP_results_passive_paired = pd.read_csv('results/20251026/CP_results_passive_paired.csv')
del CP_results_passive_paired['Unnamed: 0']

CP_results_passive_unpaired_ir = pd.read_csv('results/20251026/CP_results_passive_unpaired_ir.csv')
del CP_results_passive_unpaired_ir['Unnamed: 0']

CP_results_passive_unpaired_raman = pd.read_csv('results/20251026/CP_results_passive_unpaired_raman.csv')
del CP_results_passive_unpaired_raman['Unnamed: 0']



CP_results = pd.concat([
    CP_results_active_paired,
    CP_results_active_unpaired_ir,
    CP_results_active_unpaired_raman,
    CP_results_passive_paired,
    CP_results_passive_unpaired_ir,
    CP_results_passive_unpaired_raman
], axis=0).reset_index(drop=True)
CP_results

,id,prection_set_ir,prection_set_raman,prection_set_mvcp,polymer_flopp,hqi_flopp,id_top_match_flopp,polymer_slopp,hqi_slopp,id_top_match_slopp
0,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...,['Polymethyl Methacrylate'],"['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Polymethyl Methacrylate', 'Polyurethane', 'R...",Polymethyl Methacrylate,0.918139,PMMA 1. Orange Fragment.CSV,Polyamide,0.908069,Polyamide 1. Blue Fragment.txt
1,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...,"['Polystyrene', 'Polyurethane']","['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Polyamide', 'Polystyrene', 'Polyurethane']",Polystyrene,0.906415,PS 8. White Foam.CSV,Polyvinyl Chloride,0.919405,Polyvinyl Chloride 2. Clear Fragment.txt
2,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...,"['Polypropylene', 'Polystyrene', 'Polyurethane']","['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Acrylonitrile Butadiene Styrene', 'Polypropy...",Polypropylene,0.906320,PP 38. Blue Fragment.CSV,Polypropylene,0.914084,Polypropylene 14. Green Fiber.txt
3,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...,"['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Acrylic', 'Acrylonitrile Butadiene Styrene',...",Polypropylene,0.909396,PP 23. Yellow Fragment.CSV,Polypropylene,0.913821,Polypropylene 14. Green Fiber.txt
4,MEC_04_023_DC_Active_20241212_S2_GridSi_202502...,"['Polymethyl Methacrylate', 'Polyurethane', 'R...","['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Polymethyl Methacrylate', 'Polyurethane', 'R...",Polymethyl Methacrylate,0.905225,PMMA 1. Orange Fragment.CSV,Polypropylene,0.912531,Polypropylene 14. Green Fiber.txt
...,...,...,...,...,...,...,...,...,...,...
11244,DC_passive_MarApr2024_C9_20240612_192,NaN,"['Polyamide', 'Polyethylene', 'Polyethylene Vi...",NaN,NaN,NaN,NaN,Rubber,0.931361,Rubber 3. Red Fiber (Styrene-Isoprene).txt
11245,DC_passive_MarApr2024_C9_20240612_195,NaN,"['Acrylic', 'Acrylonitrile Butadiene Styrene',...",NaN,NaN,NaN,NaN,Polypropylene,0.916357,Polypropylene 14. Green Fiber.txt
11246,DC_passive_MarApr2024_C9_20240612_197,NaN,"['Acrylic', 'Acrylonitrile Butadiene Styrene',...",NaN,NaN,NaN,NaN,Polypropylene,0.917183,Polypropylene 14. Green Fiber.txt
11247,DC_passive_MarApr2024_C9_20240612_198,NaN,"['Acrylic', 'Acrylonitrile Butadiene Styrene',...",NaN,NaN,NaN,NaN,Polypropylene,0.908972,Polypropylene 14. Green Fiber.txt
11248,DC_passive_MarApr2024_C9_20240612_202,NaN,"['Acrylic', 'Acrylonitrile Butadiene Styrene',...",NaN,NaN,NaN,NaN,Polypropylene,0.917218,Polypropylene 14. Green Fiber.txt

In [37]:

CP_results_active_paired = pd.read_csv('results/20251110/CP_Rubber_results_active_paired.csv')
del CP_results_active_paired['Unnamed: 0']

CP_results_active_unpaired_ir = pd.read_csv('results/20251110/CP_Rubber_results_active_unpaired.csv')
del CP_results_active_unpaired_ir['Unnamed: 0']

#CP_results_active_unpaired_raman = pd.read_csv('results/20251110/CP_results_active_unpaired_raman.csv')
#del CP_results_active_unpaired_raman['Unnamed: 0']


CP_results_passive_paired = pd.read_csv('results/20251110/CP_Rubber_results_passive_paired.csv')
del CP_results_passive_paired['Unnamed: 0']

CP_results_passive_unpaired_ir = pd.read_csv('results/20251110/CP_Rubber_results_passive_unpaired.csv')
del CP_results_passive_unpaired_ir['Unnamed: 0']

#CP_results_passive_unpaired_raman = pd.read_csv('results/20251110/CP_results_passive_unpaired_raman.csv')
#del CP_results_passive_unpaired_raman['Unnamed: 0']



CP_results_Rubber = pd.concat([
    CP_results_active_paired,
    CP_results_active_unpaired_ir,
#    CP_results_active_unpaired_raman,
    CP_results_passive_paired,
    CP_results_passive_unpaired_ir,
#    CP_results_passive_unpaired_raman
], axis=0).reset_index(drop=True)
CP_results_Rubber

                                                     id prection_set_raman
0     MEC_04_023_DC_Active_20241212_S2_GridSi_202502...                 []
1     MEC_04_023_DC_Active_20241212_S2_GridSi_202502...                 []
2     MEC_04_023_DC_Active_20241212_S2_GridSi_202502...                 []
3     MEC_04_023_DC_Active_20241212_S2_GridSi_202502...                 []
4     MEC_04_023_DC_Active_20241212_S2_GridSi_202502...                 []
...                                                 ...                ...
7636              DC_passive_MarApr2024_C9_20240612_189                 []
7637              DC_passive_MarApr2024_C9_20240612_195                 []
7638              DC_passive_MarApr2024_C9_20240612_197                 []
7639              DC_passive_MarApr2024_C9_20240612_198         ['Rubber']
7640              DC_passive_MarApr2024_C9_20240612_202                 []

[7641 rows x 2 columns]

In [44]:

CP_results_active_paired = pd.read_csv('results/20260507/CP_results_active_paired.csv')
del CP_results_active_paired['Unnamed: 0']

CP_results_active_unpaired_ir = pd.read_csv('results/20260507/CP_results_active_onlyIR.csv')
del CP_results_active_unpaired_ir['Unnamed: 0']

#CP_results_active_unpaired_raman = pd.read_csv('results/20251110/CP_results_active_unpaired_raman.csv')
#del CP_results_active_unpaired_raman['Unnamed: 0']


CP_results_passive_paired = pd.read_csv('results/20260507/CP_results_pasive_paired.csv')
del CP_results_passive_paired['Unnamed: 0']

CP_results_passive_unpaired_ir = pd.read_csv('results/20260507/CP_results_pasive_onlyIR.csv')
del CP_results_passive_unpaired_ir['Unnamed: 0']

#CP_results_passive_unpaired_raman = pd.read_csv('results/20251110/CP_results_passive_unpaired_raman.csv')
#del CP_results_passive_unpaired_raman['Unnamed: 0']



CP_results_Rubber = pd.concat([
    CP_results_active_paired,
    CP_results_active_unpaired_ir,
#    CP_results_active_unpaired_raman,
    CP_results_passive_paired,
    CP_results_passive_unpaired_ir,
#    CP_results_passive_unpaired_raman
], axis=0).reset_index(drop=True)
CP_results_Rubber

,pred_set,id
0,"['Polymethyl Methacrylate', 'Polypropylene', '...",MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
1,"['Polystyrene', 'Polyurethane', 'Polyvinyl Chl...",MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
2,"['Polypropylene', 'Polystyrene', 'Polyurethane']",MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
3,"['Acrylic', 'Acrylonitrile Butadiene Styrene',...",MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
4,"['Polymethyl Methacrylate', 'Polypropylene', '...",MEC_04_023_DC_Active_20241212_S2_GridSi_202502...
...,...,...
8929,['Polyamide'],IAO_passive_June2024_G7_20240725_136
8930,['Polystyrene'],IAO_passive_June2024_G7_20240725_137
8931,['Polystyrene'],IAO_passive_June2024_G7_20240725_153
8932,"['Polyamide', 'Polypropylene', 'Polystyrene']",IAO_passive_June2024_G7_20240801_6
8933,['Rubber'],IAO_passive_June2024_G7_20240801_34

In [39]:
TWP_PredictionSets.merge(CP_results_Rubber, left_on='ID', right_on='id', how='left')

,ID,NEW NAME,Sample Type,School,Month,Stage,DAR,id,prection_set_raman
0,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_3,active,DC,Aug,3.0,PTIR only,NaN,NaN
1,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_4,active,DC,Aug,3.0,PTIR only,NaN,NaN
2,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_5,active,DC,Aug,3.0,PTIR only,NaN,NaN
3,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_6,active,DC,Aug,3.0,PTIR only,NaN,NaN
4,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_8,active,DC,Dec,1.0,PTIR only,NaN,NaN
5,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_9,active,DC,Dec,1.0,PTIR only,NaN,NaN
6,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_10,active,DC,Dec,1.0,PTIR only,NaN,NaN
7,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_11,active,DC,Dec,1.0,PTIR only,NaN,NaN
8,MEC_02_119_DC_Sp_S4_GridSi_FOV1_20240424_4,TWP_1,active,DC,Apr,4.0,paired,MEC_02_119_DC_Sp_S4_GridSi_FOV1_20240424_4,[]
9,MEC_02_119_DC_Active_20240418_S4_GridSi_202410...,TWP_2,active,DC,Apr,4.0,paired,MEC_02_119_DC_Active_20240418_S4_GridSi_202410...,['Rubber']
10,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_7,active,DC,Aug,3.0,paired,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,['Rubber']
11,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_12,active,DC,Dec,1.0,paired,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,[]
12,FHS_passive_December2024_D11_20250108_126,TWP_15,passive,FHS,Dec,NaN,PTIR only,NaN,NaN
13,DC_passive_MarApr2024_C9_20240612_136,TWP_13,passive,DC,Mar,NaN,paired,DC_passive_MarApr2024_C9_20240612_136,['Rubber']
14,DC_passive_MarApr2024_C9_20240612_155,TWP_14,passive,DC,Mar,NaN,paired,DC_passive_MarApr2024_C9_20240612_155,[]
15,FHS_passive_December2024_D11_20250108_23,TWP_16,passive,FHS,Dec,NaN,paired,FHS_passive_December2024_D11_20250108_23,['Rubber']
16,FHS_passive_December2024_D11_20250108_194,TWP_17,passive,FHS,Dec,NaN,paired,FHS_passive_December2024_D11_20250108_194,['Rubber']

In [38]:
TWP_PredictionSets.merge(CP_results, left_on='ID', right_on='id', how='left')#.to_csv(directory_name + '/TWP_PredictionSets.csv')

,ID,NEW NAME,Sample Type,School,Month,Stage,DAR,id,prection_set_ir,prection_set_raman,prection_set_mvcp,polymer_flopp,hqi_flopp,id_top_match_flopp,polymer_slopp,hqi_slopp,id_top_match_slopp
0,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_3,active,DC,Aug,3.0,PTIR only,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,['Rubber'],NaN,NaN,Rubber,0.943004,R 4. Black Bridgestone Tire Fragment.CSV,NaN,NaN,NaN
1,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_4,active,DC,Aug,3.0,PTIR only,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,['Rubber'],NaN,NaN,Rubber,0.957130,R 4. Black Bridgestone Tire Fragment.CSV,NaN,NaN,NaN
2,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_5,active,DC,Aug,3.0,PTIR only,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,"['Polyethylene', 'Rubber']",NaN,NaN,Rubber,0.905404,R 17. Grey Rubber Paving.CSV,NaN,NaN,NaN
3,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_6,active,DC,Aug,3.0,PTIR only,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,['Rubber'],NaN,NaN,Rubber,0.921072,R 6. Black Bike Tire Fragment.CSV,NaN,NaN,NaN
4,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_8,active,DC,Dec,1.0,PTIR only,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,"['Polyurethane', 'Rubber']",NaN,NaN,Rubber,0.914134,R 8. White Bike Tire Fragment.CSV,NaN,NaN,NaN
5,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_9,active,DC,Dec,1.0,PTIR only,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,['Rubber'],NaN,NaN,Rubber,0.918021,R 3. White Shoe Sole Fragment.CSV,NaN,NaN,NaN
6,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_10,active,DC,Dec,1.0,PTIR only,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,['Rubber'],NaN,NaN,Rubber,0.925041,R 8. White Bike Tire Fragment.CSV,NaN,NaN,NaN
7,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_11,active,DC,Dec,1.0,PTIR only,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,['Rubber'],NaN,NaN,Rubber,0.921507,R 3. White Shoe Sole Fragment.CSV,NaN,NaN,NaN
8,MEC_02_119_DC_Sp_S4_GridSi_FOV1_20240424_4,TWP_1,active,DC,Apr,4.0,paired,MEC_02_119_DC_Sp_S4_GridSi_FOV1_20240424_4,"['Polypropylene', 'Rubber']","['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Polyethylene', 'Polypropylene', 'Rubber']",Rubber,0.914175,R 6. Black Bike Tire Fragment.CSV,Acrylic,0.919165,Acrylic 7. White Yarn.txt
9,MEC_02_119_DC_Active_20240418_S4_GridSi_202410...,TWP_2,active,DC,Apr,4.0,paired,MEC_02_119_DC_Active_20240418_S4_GridSi_202410...,"['Acrylonitrile Butadiene Styrene', 'Polyamide...","['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Acrylic', 'Acrylonitrile Butadiene Styrene',...",Polystyrene,0.908251,PS 6. White Foam.CSV,Polypropylene,0.912808,Polypropylene 14. Green Fiber.txt
10,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_7,active,DC,Aug,3.0,paired,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,"['Polyethylene', 'Polypropylene', 'Rubber']","['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Polyethylene', 'Polypropylene', 'Rubber']",Polyethylene,0.906023,PE 43. Pink Fragment.CSV,Rubber,0.922021,Rubber 3. Red Fiber (Styrene-Isoprene).txt
11,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_12,active,DC,Dec,1.0,paired,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,"['Acrylonitrile Butadiene Styrene', 'Polystyre...","['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Acrylonitrile Butadiene Styrene', 'Polystyre...",Polystyrene,0.906996,PS 6. White Foam.CSV,Rubber,0.916101,Rubber 3. Red Fiber (Styrene-Isoprene).txt
12,FHS_passive_December2024_D11_20250108_126,TWP_15,passive,FHS,Dec,NaN,PTIR only,FHS_passive_December2024_D11_20250108_126,['Rubber'],NaN,NaN,Rubber,0.922233,R 6. Black Bike Tire Fragment.CSV,NaN,NaN,NaN
13,DC_passive_MarApr2024_C9_20240612_136,TWP_13,passive,DC,Mar,NaN,paired,DC_passive_MarApr2024_C9_20240612_136,"['Polypropylene', 'Polyurethane', 'Polyvinyl C...","['Acrylonitrile Butadiene Styrene', 'Polyamide...","['Polyethylene', 'Polypropylene', 'Polyurethan...",Rubber,0.907512,R 8. White Bike Tire Fragment.CSV,Rubber,0.926055,Rubber 3. Red Fiber (Styrene-Isoprene).txt
14,DC_passive_MarApr2024_C9_20240612_155,TWP_14,passive,DC,Mar,NaN,paired,DC_passive_MarApr2024_C9_20240612_155,['Polyethylene'],"['Acrylic', 'Acrylonitrile Butadiene Styrene',...","['Polyethylene', 'Rubber']",Polyethylene,0.918574,PE 18. White Fragment.CSV,Rubber,0.905781,Rubber 3. Red Fiber (Styrene-Isoprene).txt
15,FHS_passive_December2024_D11_20250108_23,TWP_16,passive,FHS,Dec,NaN,paired,FHS_passive_December2024_D11_20250108_23,"['Polystyrene', 'Polyurethane']","['Polyamide', 'Polyethylene', 'Polyethylene Vi...","['Polystyrene', 'Polyurethane']",Polystyrene,0.910808,PS 6. White Foam.CSV,Rubber,0.929108,Rubber 3. Red Fiber (Styrene-Isoprene).txt
16,FHS_passive_December2024_D11_20250108_194,TWP_17,passive,FHS,Dec,NaN,paired,FHS_passive_December2024_D11_20250108_194,"['Cellulose Acetate', 'Polyethylene', 'Polyeth...","['Polyamide', 'Polyethylene', 'Polyethylene Vi...","['Polyethylene', 'Polyethylene Vinyl Acetate',...",Rubber,0.906038,R 13. Pink Rubber Fragment.CSV,Rubber,0.931328,Rubber 3. Red Fiber (Styrene-Isoprene).txt

In [47]:
TWP_PredictionSets.merge(CP_results_Rubber, left_on='ID', right_on='id', how='left').iloc[:, :-1].to_csv(directory_name + '/TWP_PredictionSets.csv')

,ID,NEW NAME,Sample Type,School,Month,Stage,DAR,pred_set
0,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_3,active,DC,Aug,3.0,PTIR only,['Rubber']
1,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_4,active,DC,Aug,3.0,PTIR only,['Rubber']
2,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_5,active,DC,Aug,3.0,PTIR only,"['Polyethylene', 'Rubber']"
3,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_6,active,DC,Aug,3.0,PTIR only,['Rubber']
4,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_8,active,DC,Dec,1.0,PTIR only,"['Polyurethane', 'Rubber']"
5,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_9,active,DC,Dec,1.0,PTIR only,['Rubber']
6,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_10,active,DC,Dec,1.0,PTIR only,['Rubber']
7,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_11,active,DC,Dec,1.0,PTIR only,['Rubber']
8,MEC_02_119_DC_Sp_S4_GridSi_FOV1_20240424_4,TWP_1,active,DC,Apr,4.0,paired,"['Acrylic', 'Polycarbonate', 'Polyethylene Ter..."
9,MEC_02_119_DC_Active_20240418_S4_GridSi_202410...,TWP_2,active,DC,Apr,4.0,paired,"['Acrylonitrile Butadiene Styrene', 'Polyamide..."
10,MEC_04_014_DC_Active_20240808_S3_GridSi_202410...,TWP_7,active,DC,Aug,3.0,paired,"['Polyamide', 'Polyethylene', 'Polyethylene Te..."
11,MEC_04_023_DC_Active_20241212_S1_GridSi_202502...,TWP_12,active,DC,Dec,1.0,paired,"['Acrylonitrile Butadiene Styrene', 'Polyamide..."
12,FHS_passive_December2024_D11_20250108_126,TWP_15,passive,FHS,Dec,NaN,PTIR only,['Rubber']
13,DC_passive_MarApr2024_C9_20240612_136,TWP_13,passive,DC,Mar,NaN,paired,"['Polyamide', 'Polyethylene Terephthalate', 'P..."
14,DC_passive_MarApr2024_C9_20240612_155,TWP_14,passive,DC,Mar,NaN,paired,"['Polyamide', 'Polyethylene', 'Polypropylene',..."
15,FHS_passive_December2024_D11_20250108_23,TWP_16,passive,FHS,Dec,NaN,paired,"['Polyamide', 'Polyethylene Terephthalate', 'P..."
16,FHS_passive_December2024_D11_20250108_194,TWP_17,passive,FHS,Dec,NaN,paired,"['Acrylonitrile Butadiene Styrene', 'Cellulose..."