In [62]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

In [63]:
from utils import *

In [64]:
dir_paht = 'FTIR/'
files_list = os.listdir(dir_paht)
files_list = ['_' if x[-3:] == 'CSV' else x for x in files_list]

In [74]:
#files_list.remove('_')
files_list

['SeaSand_IR_P1.SPA',
 'Cellulose IR P3.SPA',
 'SeaSand_IR_P2.SPA',
 'SeaSand_IR_P3.SPA',
 'SeaSand_IR_P4.SPA',
 'SeaSand_IR_P5.SPA',
 'cellulose IR P4.SPA',
 'Cellulose_IR_P1.SPA',
 'WindowBackground.SPA',
 'Cellulose_IR_P2.SPA',
 'Cellulose_IR_P5.SPA',
 'Quartz IR P2.SPA',
 'Quartz IR P3.SPA',
 'Quartz IR P4.SPA',
 'Quartz IR P5.SPA',
 'Chitin_IR_P1.SPA',
 'Chitin_IR_P2.SPA',
 'Chitin_IR_P3.SPA',
 'Quartz_IR_P1.SPA',
 'Chitin_IR_P4.SPA',
 'Chitin_IR_P5.SPA']

In [75]:
import spectrochempy as scp

In [125]:
poly= [
     'SeaSand',
     'Cellulose',
     'SeaSand',
     'SeaSand',
     'SeaSand',
     'SeaSand',
     'Cellulose',
     'Cellulose',
     'Background',
     'Cellulose',
     'Cellulose',
     'Quartz',
     'Quartz',
     'Quartz',
     'Quartz',
     'Chitin',
     'Chitin',
     'Chitin',
     'Quartz',
     'Chitin',
     'Chitin'
]

In [76]:
X = [scp.read_omnic(dir_paht + x) for x in files_list]

In [133]:
[X[i].name+'-'+poly[i] for i in range(len(X))]

['Picta 8-SeaSand',
 'Picta 26-Cellulose',
 'Picta 9-SeaSand',
 'Picta 10-SeaSand',
 'Picta 11-SeaSand',
 'Picta 12-SeaSand',
 'Picta 27-Cellulose',
 'Picta 25-Cellulose',
 'Picta 20-Background',
 'Picta 25-Cellulose',
 'Picta 28-Cellulose',
 'Picta 30-Quartz',
 'Picta 31-Quartz',
 'Picta 33-Quartz',
 'Picta 33-Quartz',
 'Picta 15-Chitin',
 'Picta 16-Chitin',
 'Picta 16-Chitin',
 'Picta 29-Quartz',
 'Picta 18-Chitin',
 'Picta 19-Chitin']

In [162]:
df = pd.DataFrame({X[i].name+'.'+str(i)+'_'+poly[i]:X[i].data[0] for i in range(len(X))})
df['wavelength'] = X[0].x.data
df.columns = df.columns.str.lower()
df = df.melt('wavelength')
df['polymer'] = [x[(x.find('_')+1):] for x in df['variable']]
df.columns = ['wavelength', 'file_name', 'intensity', 'polymer']

In [167]:
df

       wavelength           file_name  intensity  polymer
0        3999.809   picta 8.0_seasand  26.329323  seasand
1        3997.880   picta 8.0_seasand  26.330128  seasand
2        3995.952   picta 8.0_seasand  26.327171  seasand
3        3994.023   picta 8.0_seasand  26.341173  seasand
4        3992.095   picta 8.0_seasand  26.342386  seasand
...           ...                 ...        ...      ...
36220     682.706  picta 19.20_chitin  63.677460   chitin
36221     680.778  picta 19.20_chitin  63.457417   chitin
36222     678.849  picta 19.20_chitin  65.348671   chitin
36223     676.921  picta 19.20_chitin  65.118439   chitin
36224     674.992  picta 19.20_chitin  64.396423   chitin

[36225 rows x 4 columns]

In [168]:

#df = pd.merge(df, inventory, how='left', left_on='variable', right_on='.SPA file name')
#df = df.drop(columns='.SPA file name')

df.to_csv('hqi_spectra.csv')

In [169]:
df_norm = norm_spect(df, norm_type='SNV')
df_norm_pivot = df_norm.pivot(index=['file_name', 'polymer'], 
               columns='wavelength', 
               values='intensity').reset_index()

In [170]:
df_norm_pivot

wavelength,file_name,polymer,674.992,676.921,678.849,680.778,682.706,684.635,686.563,688.492,...,3982.452,3984.381,3986.309,3988.238,3990.166,3992.095,3994.023,3995.952,3997.88,3999.809
0,picta 10.3_seasand,seasand,1.501969,1.601037,1.698539,1.788785,1.919268,1.957508,1.714130,1.531008,...,0.726111,0.725138,0.724175,0.722311,0.722123,0.722064,0.720512,0.721286,0.722849,0.722126
1,picta 11.4_seasand,seasand,0.269170,0.111166,-0.206963,-0.094482,0.182513,0.340827,0.173531,-0.106892,...,0.928271,0.929933,0.929048,0.929851,0.931297,0.930185,0.929079,0.927615,0.928443,0.931074
2,picta 12.5_seasand,seasand,0.512270,0.429653,0.383154,0.263828,0.373792,0.415796,0.257881,0.201827,...,0.828917,0.829157,0.828642,0.830079,0.833405,0.832331,0.829361,0.829878,0.829899,0.827998
3,picta 15.15_chitin,chitin,0.714634,0.665856,0.601741,0.596675,0.760116,0.786906,0.751227,0.701401,...,0.626316,0.624050,0.620961,0.617664,0.618374,0.619193,0.616419,0.611576,0.608846,0.606805
4,picta 16.16_chitin,chitin,1.012545,1.064663,1.100114,1.127066,1.142538,1.052342,0.961934,0.984165,...,0.901471,0.900665,0.898319,0.896879,0.895314,0.892027,0.889372,0.888523,0.885735,0.880507
5,picta 16.17_chitin,chitin,2.193491,2.296585,2.384486,2.239836,2.023351,2.100229,2.263968,2.306874,...,0.516922,0.517265,0.519745,0.517856,0.514532,0.513864,0.512597,0.509294,0.504734,0.499573
6,picta 18.19_chitin,chitin,3.084660,3.031201,3.139437,3.215127,3.219615,3.124476,3.117781,3.071504,...,0.581562,0.580726,0.577893,0.576006,0.575103,0.573135,0.572282,0.571451,0.567884,0.563237
7,picta 19.20_chitin,chitin,3.502037,3.574032,3.596989,3.408405,3.430346,3.493125,3.535890,3.472971,...,0.443433,0.444163,0.443788,0.438859,0.435508,0.434663,0.433666,0.431142,0.427931,0.425412
8,picta 20.8_background,background,-2.440545,-2.439901,-2.439639,-2.439297,-2.439242,-2.439106,-2.439599,-2.439171,...,-0.995371,-0.997559,-1.000118,-1.002021,-1.004645,-1.006657,-1.008462,-1.010472,-1.012455,-1.014481
9,picta 25.7_cellulose,cellulose,0.347438,0.377782,0.296791,0.356229,0.307569,0.286895,0.346513,0.414003,...,0.900424,0.895467,0.893910,0.892059,0.887514,0.883185,0.878724,0.873767,0.865061,0.858341
10,picta 25.9_cellulose,cellulose,0.347438,0.377782,0.296791,0.356229,0.307569,0.286895,0.346513,0.414003,...,0.900424,0.895467,0.893910,0.892059,0.887514,0.883185,0.878724,0.873767,0.865061,0.858341
11,picta 26.1_cellulose,cellulose,0.812234,0.845077,0.748222,0.708187,0.694712,0.615261,0.552903,0.653028,...,0.922989,0.918411,0.913065,0.907582,0.902684,0.903530,0.901549,0.895502,0.891462,0.884989
12,picta 27.6_cellulose,cellulose,-0.072864,-0.273840,-0.350682,-0.128092,-0.078504,-0.135824,-0.174264,-0.126146,...,0.900058,0.895639,0.895293,0.892807,0.885039,0.877275,0.871818,0.867401,0.862199,0.854713
13,picta 28.10_cellulose,cellulose,0.507811,0.363146,0.446522,0.569338,0.408272,0.300658,0.369247,0.417904,...,0.876625,0.874120,0.868272,0.862517,0.860273,0.855478,0.849014,0.844631,0.841188,0.837744
14,picta 29.18_quartz,quartz,0.619300,0.561322,0.558153,0.536731,0.666600,0.620504,0.633148,0.652339,...,0.822381,0.820179,0.818933,0.817811,0.816806,0.817892,0.819374,0.819366,0.818835,0.818431
15,picta 30.11_quartz,quartz,0.830728,0.675617,0.390276,0.446513,0.611228,0.540219,0.609911,0.700084,...,0.811032,0.808972,0.810332,0.809976,0.808400,0.810016,0.812351,0.813079,0.810548,0.806479
16,picta 31.12_quartz,quartz,0.338091,0.295511,0.084049,-0.055855,-0.008667,-0.052563,0.029904,0.281553,...,0.912201,0.908059,0.911199,0.917784,0.917419,0.914370,0.914868,0.915185,0.913423,0.912480
17,picta 33.13_quartz,quartz,-0.180043,-0.176711,-0.070945,-0.007261,-0.058361,-0.052230,-0.059676,-0.070417,...,0.852283,0.852002,0.850927,0.851017,0.851210,0.851943,0.852194,0.850887,0.850454,0.850813
18,picta 33.14_quartz,quartz,0.842479,0.447804,0.202995,0.270512,0.470781,0.660923,0.771989,0.437585,...,0.803357,0.803037,0.803392,0.803471,0.802072,0.802700,0.804564,0.803817,0.802763,0.803247
19,picta 8.0_seasand,seasand,1.522616,1.498333,1.452992,1.332951,1.338940,1.398967,1.365131,1.184738,...,0.840052,0.841108,0.838436,0.835171,0.835232,0.837498,0.837382,0.836046,0.836328,0.836252
20,picta 9.2_seasand,seasand,1.107090,1.067599,1.262814,1.202717,1.132989,1.156984,1.190999,1.234569,...,0.769351,0.769238,0.768762,0.768025,0.767805,0.768906,0.770713,0.770692,0.769397,0.768691