In [1]:
import pandas as pd

In [7]:
polymer_short_names = ['PEVA',
                          'Nylon',
                          'PVC',
                          'PE',
                          'PET',
                          'PLA',
                          'PS',
                          'Acrylic',
                          'Cotton',
                          'Polyester',
                          'ABS',
                          'PU',
                          'PEA',
                          'R',
                          'PC',
                          'PP',
                          'PA',
                          'PMMA',
                          'PVA',
                          'PBT']
  
polymer_names = ['Polyethylene Vinyl Acetate',
                    'Nylon',
                    'Polyvinyl Chloride', 
                    'Polyethylene', 
                    'Polyethylene Terephthalate', 
                    'Polylactic acid', 
                    'Polystyrene', 
                    'Acrylic', 
                    'Cotton', 
                    'Polyester', 
                    'Acrylonitrile Butadiene Styrene', 
                    'Polyurethane', 
                    'Polyethylene Adipate', 
                    'Styrene-butadiene Rubber', 
                    'Polycarbonate', 
                    'Polypropylene',
                    'Polyamide',
                    'Polymethyl Methacrylate',
                    'Polyvinyl Acetate',
                    'Polybutylene Terephthalate']

dict_pol_names = pd.DataFrame({'pol_short_names':polymer_short_names, 'polymer':polymer_names})
dict_pol_names

   pol_short_names                          polymer
0             PEVA       Polyethylene Vinyl Acetate
1            Nylon                            Nylon
2              PVC               Polyvinyl Chloride
3               PE                     Polyethylene
4              PET       Polyethylene Terephthalate
5              PLA                  Polylactic acid
6               PS                      Polystyrene
7          Acrylic                          Acrylic
8           Cotton                           Cotton
9        Polyester                        Polyester
10             ABS  Acrylonitrile Butadiene Styrene
11              PU                     Polyurethane
12             PEA             Polyethylene Adipate
13               R         Styrene-butadiene Rubber
14              PC                    Polycarbonate
15              PP                    Polypropylene
16              PA                        Polyamide
17            PMMA          Polymethyl Methacrylate
18             PVA                Polyvinyl Acetate
19             PBT       Polybutylene Terephthalate

In [13]:
polymer_short_names_e = ['PVC',
                         'PE',
                         'PET',
                         'ABS',
                         'PU',
                         'PC',
                         'C',
                         'PMMA',
                         'CA',
                         'EAA',
                         'SR',
                         'EVA',
                         'PS',
                         'PA',
                         'PP'] #list(set([x.split(' ', 1)[0] for x in files_flopp]))                      

polymer_names_e = ['Polyvinyl Chloride',
                   'Polyethylene', 
                   'Polyethylene Terephthalate', 
                   'Acrylonitrile Butadiene Styrene', 
                   'Polyurethane',
                   'Polycarbonate', 
                   'Cotton',
                   'Polymethyl Methacrylate',
                   'Cellulose Acetate',
                   'Ethylene Acrylic Acid',
                   'SR',
                   'Polyethylene Vinyl Acetate', 
                   'Polystyrene',
                   'Polyamide',
                   'Polypropylene']
dict_pol_names_e = pd.DataFrame({'pol_short_names':polymer_short_names_e, 'polymer':polymer_names_e})
dict_pol_names_e

   pol_short_names                          polymer
0              PVC               Polyvinyl Chloride
1               PE                     Polyethylene
2              PET       Polyethylene Terephthalate
3              ABS  Acrylonitrile Butadiene Styrene
4               PU                     Polyurethane
5               PC                    Polycarbonate
6                C                           Cotton
7             PMMA          Polymethyl Methacrylate
8               CA                Cellulose Acetate
9              EAA            Ethylene Acrylic Acid
10              SR                               SR
11             EVA       Polyethylene Vinyl Acetate
12              PS                      Polystyrene
13              PA                        Polyamide
14              PP                    Polypropylene

In [15]:
dict_polymers = pd.merge(dict_pol_names, dict_pol_names_e, how='outer').sort_values('pol_short_names')
dict_polymers.to_csv('dict_polymers.csv')

In [22]:
polymer_list = pd.DataFrame({'polymer':['Polyethylene',
 'Polyethylene Vinyl Acetate',
 'Polyvinyl Chloride',
 'Polyamide',
 'Acrylonitrile Butadiene Styrene',
 'Polymethyl Methacrylate',
 'Polycarbonate',
 'Polyester',
 'Cotton',
 'Polypropylene',
 'Cellulose Acetate',
 'Polystyrene',
 'Polyurethane',
 'Acrylic',
 'Polyethylene Terephthalate'], 'test':1})

In [23]:
pd.isinpolymer_list

                            polymer  test
0                      Polyethylene     1
1        Polyethylene Vinyl Acetate     1
2                Polyvinyl Chloride     1
3                         Polyamide     1
4   Acrylonitrile Butadiene Styrene     1
5           Polymethyl Methacrylate     1
6                     Polycarbonate     1
7                         Polyester     1
8                            Cotton     1
9                     Polypropylene     1
10                Cellulose Acetate     1
11                      Polystyrene     1
12                     Polyurethane     1
13                          Acrylic     1
14       Polyethylene Terephthalate     1

In [24]:
pd.merge(dict_polymers, polymer_list, how='outer')

   pol_short_names                          polymer  test
0              ABS  Acrylonitrile Butadiene Styrene   1.0
1          Acrylic                          Acrylic   1.0
2                C                           Cotton   1.0
3           Cotton                           Cotton   1.0
4               CA                Cellulose Acetate   1.0
5              EAA            Ethylene Acrylic Acid   NaN
6              EVA       Polyethylene Vinyl Acetate   1.0
7             PEVA       Polyethylene Vinyl Acetate   1.0
8            Nylon                            Nylon   NaN
9               PA                        Polyamide   1.0
10             PBT       Polybutylene Terephthalate   NaN
11              PC                    Polycarbonate   1.0
12              PE                     Polyethylene   1.0
13             PEA             Polyethylene Adipate   NaN
14             PET       Polyethylene Terephthalate   1.0
15             PLA                  Polylactic acid   NaN
16            PMMA          Polymethyl Methacrylate   1.0
17              PP                    Polypropylene   1.0
18              PS                      Polystyrene   1.0
19              PU                     Polyurethane   1.0
20             PVA                Polyvinyl Acetate   NaN
21             PVC               Polyvinyl Chloride   1.0
22       Polyester                        Polyester   1.0
23               R         Styrene-butadiene Rubber   NaN
24              SR                               SR   NaN